### ISSUE TITLE
REW Import not working

### ISSUE THREAD

**Issue by cableffm** [pulento/A1Evo_Electrified#1]
Hi Juanjo, 

I'll contact you here because I don't want to derail the OCA thread over at AVS :)

First, thank you for this tool!

But I'm experiencing a problem:
Since 0.9.6 the REW import no longer works. Neither with 0.9.6 nor with 0.9.7 / REW b46 and b48
I revo uninstalled everything completely and started from scratch. Won't work anymore. 
This is on 13900K on Z790 with Win11 Pro .
Hopefully you have an idea :)

Edit: I've tried 0.9.5 and it works perfectly fine.

Best
Tom

**Comment by pulento** [comment]
Hi,

Please attach your .ady and logs to replicate your problem.

**Comment by cableffm** [comment]
Good Morning :)
Ofcourse. Here are my 2 .ady-files which doesnt work with 0.9.6 and 0.9.7, but with 0.9.5 and their logs from 0.9.5.
Please let me know if you need anything else.
Thanks in advance and kind regards
Tom

[Adys.zip](https://github.com/user-attachments/files/16519274/Adys.zip)
[A1Evo_Electrified_Log.txt](https://github.com/user-attachments/files/16519426/A1Evo_Electrified_Log.txt)
[A1Evo_Electrified_Log2.txt](https://github.com/user-attachments/files/16519485/A1Evo_Electrified_Log2.txt)

**Comment by pulento** [comment]
Thanks to report the Issue here, the AVS forum thread is a nightmare to follow and I really don't want to worsten things there.

Remember to select the target curve on A1EE since now its autoload by A1EE, if you usually use the same TC set it on your Settings so every time you start it will be selected, just click in the target curve input box to open the file selector:

<img width="765" alt="Screenshot 2024-08-07 at 10 55 49" src="https://github.com/user-attachments/assets/31853023-df3d-4b3d-8fbb-16e722e953de">

Here is the log warning you about no target curve loaded:

```
08:48:01 [WARNING!] Target curve not found! Browse to and select 'Evo3_TargetCurve.txt' (or any other) in 'REW / EQ window / House curve'!
08:48:01 [IMPORTANT!] Click 'Optimize calibration' button again when ready.


```

**Comment by cableffm** [comment]
Aaah got it!  My bad :)
I've to select the target curve BEFORE the "upload calibration" button.
Now it works perfectly.
Thanks a lot!

**Comment by pulento** [comment]
Yes.

Better to set it on your preferences so you don't have to set it every time you run it.

**Comment by cableffm** [comment]
Discovered that as well  thanks to your reply :)
What a great and helpful addon / upgrade for A1E! Thx again
