### ISSUE TITLE
A1EE on Windows cannot import TargetCurve if older settings are present

### ISSUE THREAD

**Issue by ManCaveAudio** [pulento/A1Evo_Electrified#2]
[2x4 hd + EQ 21-Jun.ady.txt](https://github.com/user-attachments/files/16576670/2x4.hd.%2B.EQ.21-Jun.ady.txt)
1. This is the first time I am not able to open the attached ady file in Electrified
2. When I boot electrified, I see a green square box (this is a bug or what I don't know). Just informing.
3. TODO: Implement input boxes and settings for custom crossovers: Unable to find this setting in the electrified
4. Edit: Not able to load any Ady fFile. Once I click Upload Calibration, nothing happens.

I also ensured that the REW & API Server was on.

**Comment by pulento** [comment]
Will check your ADY, here there is no need to post with .txt here also please attach you log.

The green box is the first time you run a new version. It's the installer running, don't need to run the Setup.exe file everytime, since it installs in your Apps and set a shortchut in case of Windows. Use that shortcut thereafter.

Number 3 is a TODO (to do), means that in the next releases I'll do that.

**Comment by ManCaveAudio** [comment]
I am not ale to Not able to load any Ady fFile. Once I click Upload Calibration, nothing happens.
I also ensured that the REW & API Server was on.

Getting this error.

Failed to load resource: the server responded with a status of 400 (Bad Request)
renderer.js:31609 

Uncaught (in promise) Error
    at postSafe (renderer.js:31609:11)
    at async extractAdy (renderer.js:182:3)

**Comment by pulento** [comment]
Ok,

Worked fine on MacOS and not on Windows 11.

Basically because you got an older A1EE installed, pointing to a TargetCurve that was deleted by the uninstaller/installer, please select your curve again.

This happens because the App directory resources where targetcurves resides is tied to the version of the App so your settings where pointing to the old directory which doesn't exist.

Selecting the curve on the inputbox or settings should fix your problem.

Please report. I'll take me some time to implement some sort of settings upgrade everytime you upgrade on Windows or simply delete the settings file to get the defaults on every install.

**Comment by ManCaveAudio** [comment]
Ok, I have uninstalled A1EE, still getting the same Error. I am using Windows 10.

The selected target curve, as you suggested, is still not EE and is not working.

This is the first time happening among all versions of EE I used.

**Comment by ManCaveAudio** [comment]
One more issue: If REW is already open, EE will open a new REW window.

**Comment by pulento** [comment]
No need to uninstall. This will happens on W10 or W11.

Are you using a custom target curve which is in another directory ?

I replicated your problem. And simply clicked the Target Curve inputbox which sends you to the "new" directory with the canned TCs (which happens to change with every version of A1EE on Windows)

**Comment by pulento** [comment]
> One more issue: If REW is already open, EE will open a new REW window.

A1EE opens REW when is ran with the API started no need to have REW open. And closes the REW instance it ran when you close it. If there is another REW running it will run another instance.

**Comment by pulento** [comment]
Easier,

Select setting on A1EE and choose a TC. Then exit and reopen. It should have saved the TC path; like these (note the 0.9.8 on the path):

<img width="693" alt="Screenshot 2024-08-11 at 10 05 50 PM" src="https://github.com/user-attachments/assets/e2c9535b-fbc2-4e1d-9bcc-e48968202b1b">

**Comment by ManCaveAudio** [comment]
I am using Windows 10

This works now. I selected another target curve. By default, it was showing me HarmanKardenTC. I changed it to another TC and it started working.

**Comment by ManCaveAudio** [comment]
I don't know how you are going to implement custom Xo...but give drop box to select pre-defined Xo so users cannot enter wrong Xo like 50,70 etc.....

**Comment by pulento** [comment]
> I am using Windows 10
> 
> This works now. I selected another target curve. By default, it was showing me HarmanKardenTC. I changed it to another TC and it started working.

Thanks,

The settings are keep even if you uninstall/reinstall, problem is that if your TC was on the older resources app directory it will point to a file that don't exist anymore. Need to figure out which is better, wipe the settings on every install or something more sophisticated like clearing just the TC path on settings.

This doesn't happens on MacOS since Mac resources files don't have the app version.

**Comment by pulento** [comment]
> I don't know how you are going to implement custom Xo...but give drop box to select pre-defined Xo so users cannot enter wrong Xo like 50,70 etc.....

That's another point/enhacement. Need to study the correct values. AFAIK on the code there is a range but that range is evaluated on specific frecuencies by A1Evo, but why ? It seem that Denon/Marantz allows only those combinations.
